### PR TITLE
Django 1.8 support

### PR DESCRIPTION
**Pull request by fellowshipofone**

### CODE REVIEW

**Comment by grjones** [comment]
This patch for Django 1.8.3 does not appear to work if called within a `transaction.atomic` block.  The error I am seeing is below.  Using:
kombu==3.0.26
celery==3.1.18
django_celery==3.1.16
django-celery-transactions==0.3.2
celery_haystack==0.9
django-haystack==2.4.0
```
  File "/opt/virtualenvs/foo/local/lib/python2.7/site-packages/djcelery_transactions/transaction_signals.py", line 95, in __patched__exit__
    transaction.signals.post_commit.send(None)
  File "/opt/virtualenvs/foo/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/opt/virtualenvs/foo/local/lib/python2.7/site-packages/djcelery_transactions/__init__.py", line 138, in _send_tasks
    tsk.original_apply_async(*args, **kwargs)
  File "/opt/virtualenvs/foo/local/lib/python2.7/site-packages/djcelery_transactions/__init__.py", line 51, in original_apply_async
    return super(PostTransactionTask, self).apply_async(*args, **kwargs)
  File "/opt/virtualenvs/foo/local/lib/python2.7/site-packages/celery/app/task.py", line 559, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/opt/virtualenvs/foo/local/lib/python2.7/site-packages/celery/app/base.py", line 353, in send_task
    reply_to=reply_to or self.oid, **options
  File "/opt/virtualenvs/foo/local/lib/python2.7/site-packages/celery/app/amqp.py", line 305, in publish_task
    **kwargs
  File "/opt/virtualenvs/foo/local/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/opt/virtualenvs/foo/local/lib/python2.7/site-packages/kombu/connection.py", line 436, in _ensured
    return fun(*args, **kwargs)
  File "/opt/virtualenvs/foo/local/lib/python2.7/site-packages/kombu/messaging.py", line 188, in _publish
    mandatory=mandatory, immediate=immediate,
  File "/opt/virtualenvs/foo/local/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 521, in basic_publish
    message, exchange, routing_key, **kwargs
  File "/opt/virtualenvs/foo/local/lib/python2.7/site-packages/kombu/transport/virtual/exchange.py", line 61, in deliver
    _put(queue, message, **kwargs)
  File "/opt/virtualenvs/foo/local/lib/python2.7/site-packages/kombu/transport/django/__init__.py", line 39, in _put
    Queue.objects.publish(queue, dumps(message))
  File "/opt/virtualenvs/foo/local/lib/python2.7/site-packages/kombu/transport/django/managers.py", line 29, in publish
    queue.messages.create(payload=payload)
  File "/opt/virtualenvs/foo/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 758, in create
    return super(RelatedManager, self.db_manager(db)).create(**kwargs)
  File "/opt/virtualenvs/foo/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/virtualenvs/foo/local/lib/python2.7/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/virtualenvs/foo/local/lib/python2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/virtualenvs/foo/local/lib/python2.7/site-packages/django/db/models/base.py", line 735, in save_base
    with transaction.atomic(using=using, savepoint=False):
  File "/opt/virtualenvs/foo/local/lib/python2.7/site-packages/django/db/transaction.py", line 164, in __enter__
    "The outermost 'atomic' block cannot use "
TransactionManagementError: The outermost 'atomic' block cannot use savepoint = False when autocommit is off.
```

**Comment by fellowshipofone** [comment]
thanks @grjones, what DB are you using? From the look of it, you are maybe using SQLite?

the error is more likely due to DB transaction settings than to `django-celery-transactions` since no `atomic` block is added

**Comment by grjones** [comment]
@fellowshipofone Thanks for the quick response!  I'm using PostgreSQL 9.4.

**Comment by fellowshipofone** [comment]
Do you mind sharing your DB settings? (comment out username/pass/hostname obviously)

**Comment by grjones** [comment]
Sure.  Here you go:
```
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'pr',
        'USER': 'django',
        'PASSWORD': os.environ.get('PGPASSWORD'),
        'HOST': '%s' % HOST,
        'PORT': int(PORT),
    }
}
```
Using psycopg2==2.5.4

**Comment by fellowshipofone** [comment]
Alright, I just ran the tests with Django 1.8.3 and I don't have any failure. Coverage is not 100%, but nowhere in the code do I set autocommit to False.

Any chance you'd be playing with that setting in your code?

https://docs.djangoproject.com/en/1.8/topics/db/transactions/#managing-autocommit

(will have to get back to you a little later next time unfortunately)

**Comment by grjones** [comment]
I'm using default autocommit behavior.  I think `atomic()` (without monkeypatching) sets autocommit to False.

**Comment by fellowshipofone** [comment]
I've seen this happening when running tests with sqlite3.

I see one new commit that could have changed but I do not think it will be merged before Django 1.9:
https://github.com/django/django/commit/00a1d4d042a7afd139316982c9b57e87d26a894f

I'll need to look a little more at it. If you could share with me a simple test that fails, that would help a lot

**Pull request merged**
